version: '3'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.1"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      cluster.name: rome
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - elastic_data:/usr/share/elasticsearch/data      

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.1.1"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}

volumes:
  elastic_data: